### ISSUE TITLE
It not working,Help!

### ISSUE THREAD

**Issue by ChikoHeartCN** [OnofriAndreaPG/drcte#1]
![image](https://user-images.githubusercontent.com/89725802/147349408-ac41dc3a-388b-4212-9d58-c7e69fbd7e04.png)
Error to install this package,Please give me some advice.Thanks!

**Comment by OnofriAndreaPG** [comment]
Hello,

at the moment, you have to install drcSeedGerm first, by using the following code:

devtools::install_github("OnofriAndreaPG/drcSeedGerm”)

afterwards, you can install drcte. This should solve your problem, hopefully. Lately, I have to remove such dependency or improve the installation instructions (lack of time, sorry).

Besta

Andrea

**Comment by OnofriAndreaPG** [comment]
The dependency from drcSeedGerm has been removed.
